import { Box } from '@mui/material'
import React from 'react'
import StudentSidebar from '../../Navs/Sidebar/StudentSidebar'
import { AboutContent, AboutHeader, AboutHeaderContainer, AboutHeaderContent, AboutImage, AboutImageBox, AboutImageContainer, AboutImageContent, AboutInfo, AboutParagraph, AboutParagraphBox, AboutParagraphContent, ContactUsContent, WelcomeHeader } from '../Common'
import styled from 'styled-components'
import ContactUs from '../ContactUs'
import { Marginer } from '../../Marginer/Margin'


function AboutUsStudent() {
  return (
    <Box sx={{ display: 'flex' }}>
      <StudentSidebar/>
      <Box component='main' sx={{flexGrow: 1, p: 3}}>
        <AboutContent>
          <AboutHeaderContent>
            <WelcomeHeader>About Attendance Management Systems:</WelcomeHeader>
          </AboutHeaderContent>
        </AboutContent>
        <AboutParagraphContent>
          <AboutParagraphBox>
            <AboutParagraph>
              Attendance Management System: Leveraging QR Code Technology for Streamlined Classroom Monitoring is a system designed to use QR technology to monitor real-time classroom activity. The system will integrate QR technology to automate and simplify the task of tracking and managing students’ attendance.
            </AboutParagraph>
            <AboutParagraph>
              Here is how the system work:
              QR Code Generation: Generated unique QR codes to scan for each course and class. 
              The codes will be generated by the use of specific software and programming tools. 
              Displaying QR Codes: Provides course and subjects unique QR codes that can be printed or distributed online. 
              Attendance Tracking: To mark attendance, Professors of Instructors will provide QR code that is either printed or on a screen. The code represents the class session of a specific time slot. 
              Scanning QR Codes: The students will be provided with a mobile app to use as a scanner and send the data to the database. QR scanning will be done upon entering the classroom. 
              Real-time Data Capture: As someone scans the QR codes, the system will record the data real-time as it will be stored in a database. 
              Monitoring Analysis: Professors, Instructors, and Authorized personnel can access and manipulate data in the system by the use of website integrated system to view the data from the database. 
              Features: The Attendance Management System will have the following features: 
              • User Modules 
              • Login/Signup Modules 
              • QR Code Generation 
              • Attendance Tracking 
              • Reporting and Analytics 
              • Interactive UI 
              • Integration with Student Information System (SIS) 
              • Mobile Application • Data Security and Privacy 
              • Dashboards 
              • Integration with Timetable Management
            </AboutParagraph>
            <AboutParagraph>
            Target Users: • Students • Professors/Instructors • Database Administrators
            </AboutParagraph>
          </AboutParagraphBox>
        </AboutParagraphContent>
        <Marginer direction="vertical" margin={'1px'}/>
        <AboutContent>
          <AboutHeaderContent>
            <WelcomeHeader>About Us:</WelcomeHeader>
          </AboutHeaderContent>
        </AboutContent>
        <Marginer direction="vertical" margin={'1px'}/>
        <AboutImageBox>
          <AboutImageContent>
            <AboutImageContainer>
              <AboutHeaderContainer>
                <AboutImage src="https://scontent.fcrk2-2.fna.fbcdn.net/v/t39.30808-6/306005286_5659702014065707_4378458342993441244_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=1b51e3&_nc_eui2=AeGTQ11HUE5FbGfiLBa1oZNQKzr4dgyur4YrOvh2DK6vhhRgnuPLFYwF6HwSE2UnIXbOMqrQK96sLTJufnTCpSEP&_nc_ohc=4x9dJP0lDaEAX_2fFjf&_nc_ht=scontent.fcrk2-2.fna&oh=00_AfBzv27Ez23YsCwxgTKu65HCeF5TyqVONhWQxkVIQKj5Zw&oe=65142152" alt=""/>
                <AboutHeader>Job Gian C. Dispo</AboutHeader>
                <AboutInfo>Project Manager</AboutInfo>
                <SocialMediaContainer>
                  <SocialMediaUL>
                  <SocialMediaList>
                    <a 
                    style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                    href="https://www.facebook.com" 
                    target='_black'
                    class="fa fa-lg fa-facebook">
                    </a>
                  </SocialMediaList>
                  <SocialMediaList>
                    <a 
                    style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                    href="https://twitter.com/?lang=en" 
                    target='_black'
                    class="fa fa-lg fa-twitter">
                    </a>
                  </SocialMediaList>
                  <SocialMediaList>
                    <a 
                    style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                    href="https://github.com/mrzyphyl/Attendance-Management-System"
                    target='_black'
                    class="fa fa-lg fa-github">
                    </a>
                  </SocialMediaList>
                  <SocialMediaList>
                    <a 
                    style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                    href="https://www.linkedin.com/in/job-gian-dispo-706580284/" 
                    target='_black'
                    class="fa fa-lg fa-linkedin">
                    </a>
                  </SocialMediaList>
                  <SocialMediaList>
                    <a 
                    style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                    href="https://www.instagram.com/" 
                    target='_black'
                    class="fa fa-lg fa-instagram">
                    </a>
                  </SocialMediaList>  
                  </SocialMediaUL>
                </SocialMediaContainer>
              </AboutHeaderContainer>
            </AboutImageContainer>
            <AboutImageContainer>
              <AboutHeaderContainer>
                <AboutImage src="https://scontent.fmnl4-5.fna.fbcdn.net/v/t39.30808-6/340636617_893089635103302_9009003379311767663_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeEY9AzflDPPVA4qTJKFesqu5uP-hlMexDrm4_6GUx7EOqpNybLKze_AOuZF8Cq9w2pvPKt_cu2AStB87aIadrSr&_nc_ohc=pXdstYidewsAX-eHxA1&_nc_ht=scontent.fmnl4-5.fna&oh=00_AfCiQk2SaBJes4w96wm5ZhD6YDJHx3B-SqLcR6h4usgsvw&oe=6513EB98" alt=""/>
                <AboutHeader>Michael Kearney C. Lameg</AboutHeader>
                <AboutInfo>Systems Integrator</AboutInfo>
              </AboutHeaderContainer>
              <SocialMediaContainer>
                <SocialMediaUL>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.facebook.com" 
                  target='_black'
                  class="fa fa-lg fa-facebook">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://twitter.com/?lang=en" 
                  target='_black'
                  class="fa fa-lg fa-twitter">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://github.com/mrzyphyl/Attendance-Management-System"
                  target='_black'
                  class="fa fa-lg fa-github">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.linkedin.com/in/job-gian-dispo-706580284/" 
                  target='_black'
                  class="fa fa-lg fa-linkedin">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.instagram.com/" 
                  target='_black'
                  class="fa fa-lg fa-instagram">
                  </a>
                </SocialMediaList>  
                </SocialMediaUL>
              </SocialMediaContainer>
            </AboutImageContainer>
            <AboutImageContainer>
              <AboutHeaderContainer>
                <AboutImage src="https://indianmemetemplates.com/wp-content/uploads/happy-pepe-the-forg.jpg" alt=""/>
                <AboutHeader>Denz B. Tumbaga</AboutHeader>
                <AboutInfo>Resource Management</AboutInfo>
              </AboutHeaderContainer>
              <SocialMediaContainer>
                <SocialMediaUL>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.facebook.com" 
                  target='_black'
                  class="fa fa-lg fa-facebook">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://twitter.com/?lang=en" 
                  target='_black'
                  class="fa fa-lg fa-twitter">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://github.com/mrzyphyl/Attendance-Management-System"
                  target='_black'
                  class="fa fa-lg fa-github">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.linkedin.com/in/job-gian-dispo-706580284/" 
                  target='_black'
                  class="fa fa-lg fa-linkedin">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.instagram.com/" 
                  target='_black'
                  class="fa fa-lg fa-instagram">
                  </a>
                </SocialMediaList>  
                </SocialMediaUL>
              </SocialMediaContainer>
            </AboutImageContainer>
          </AboutImageContent>
          <AboutImageContent>
            <AboutImageContainer>
              <AboutHeaderContainer>
                <AboutImage src="https://scontent.fmnl4-5.fna.fbcdn.net/v/t39.30808-6/369191245_1698784700629459_7977540431026187716_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeHuo-ADLCmtp2ObeyHwJh8OHwu88jYTCwYfC7zyNhMLBqDGvzSzbdvsZ9d4laK0NSXPWQuvJqer4Fil8VjLYjV6&_nc_ohc=EmSwiEguYY0AX9b75Ku&_nc_ht=scontent.fmnl4-5.fna&oh=00_AfAmtWGJ1bRdxi09Ky1cnUVPDg4alrhFKTA1YZXJ2vwWZg&oe=6513D4E9" alt=""/>
                <AboutHeader>Charles Andrei J. Bautista</AboutHeader>
                <AboutInfo>Researcher</AboutInfo>
              </AboutHeaderContainer>
              <SocialMediaContainer>
                <SocialMediaUL>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.facebook.com" 
                  target='_black'
                  class="fa fa-lg fa-facebook">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://twitter.com/?lang=en" 
                  target='_black'
                  class="fa fa-lg fa-twitter">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://github.com/mrzyphyl/Attendance-Management-System"
                  target='_black'
                  class="fa fa-lg fa-github">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.linkedin.com/in/job-gian-dispo-706580284/" 
                  target='_black'
                  class="fa fa-lg fa-linkedin">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.instagram.com/" 
                  target='_black'
                  class="fa fa-lg fa-instagram">
                  </a>
                </SocialMediaList>  
                </SocialMediaUL>
              </SocialMediaContainer>
            </AboutImageContainer>
            <AboutImageContainer>
              <AboutHeaderContainer>
                <AboutImage src="https://scontent.fcrk2-1.fna.fbcdn.net/v/t39.30808-6/361595719_3618595711793923_861439001018089757_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeEh6reeRWxnLg4-rIvhFVZZqpjJNUG3xRWqmMk1QbfFFYZAELPql6a7PZpoEUCrGXXwd5Lwg16EEyOd1XmXaMWK&_nc_ohc=mSYSjNVGqwMAX8jMNEG&_nc_ht=scontent.fcrk2-1.fna&oh=00_AfCNMP12hEp2ZkJwanpCDDPd3F1CW-FiCZdKA13JpnNWNw&oe=65145F15" alt=""/>
                <AboutHeader>Franz Gian Lee T. Estrada</AboutHeader>
                <AboutInfo>Data Analyst</AboutInfo>
              </AboutHeaderContainer>
              <SocialMediaContainer>
                <SocialMediaUL>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.facebook.com" 
                  target='_black'
                  class="fa fa-lg fa-facebook">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://twitter.com/?lang=en" 
                  target='_black'
                  class="fa fa-lg fa-twitter">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://github.com/mrzyphyl/Attendance-Management-System"
                  target='_black'
                  class="fa fa-lg fa-github">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.linkedin.com/in/job-gian-dispo-706580284/" 
                  target='_black'
                  class="fa fa-lg fa-linkedin">
                  </a>
                </SocialMediaList>
                <SocialMediaList>
                  <a 
                  style={{color: '#000', textDecoration: 'none', padding: '5px'}} 
                  href="https://www.instagram.com/" 
                  target='_black'
                  class="fa fa-lg fa-instagram">
                  </a>
                </SocialMediaList>  
                </SocialMediaUL>
              </SocialMediaContainer>
            </AboutImageContainer>
          </AboutImageContent>
        </AboutImageBox>
        <Marginer direction="vertical" margin={'1px'}/>
        <AboutContent>
          <AboutHeaderContent>
            <WelcomeHeader>Contact Us:</WelcomeHeader>
          </AboutHeaderContent>
        </AboutContent>
        <Marginer direction="vertical" margin={'1px'}/>
        <ContactUsContent>
          <ContactUs/>
        </ContactUsContent>
      </Box>
    </Box>
  )
}

const SocialMediaContainer = styled.div`
  display: flex;
  gap: 0.5rem;
  align-items: center;
`

const SocialMediaUL = styled.ul`
  display: flex;
  flex-direction: row;
  padding: 5px;
  gap: 1rem;
`

const SocialMediaList = styled.li`
  list-style: none outside none;
  display: inline-block;
`

export default AboutUsStudent